services:
  db:
    image: postgres:15
    container_name: wordhunt_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: wordhunt
    ports:
      - "5432:5432"
    volumes:
      - wordhunt_db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - wordhunt-net

  backend:
    build: ./backend
    container_name: wordhunt_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:adminpassword@db:5432/wordhunt
    networks:
      - wordhunt-net

  frontend:
    image: nginx:alpine
    container_name: wordhunt_frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - wordhunt-net

networks:
  wordhunt-net:
    driver: bridge

volumes:
  wordhunt_db_data: